name: very_good_coffee_app
description: Very Good Coffee App
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.1.4
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.10
  copy_with_extension_gen: ^5.0.4
  floor_generator: ^1.5.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
